# Simple workflow for deploying static content to GitHub Pages
name: Deploy static content to Pages

on:
  push:
    branches:
      - master
  pull_request:
    types: [opened, reopened, synchronize]
    branches:
      - master
  workflow_dispatch:

# Sets permissions of the GITHUB_TOKEN to allow deployment to GitHub Pages
permissions:
  contents: read
  pages: write
  id-token: write

# Allow one concurrent deployment
concurrency:
  group: ${{ github.ref }}
  cancel-in-progress: true

jobs:
  lint-md:
    name: Lint markdown
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: markdownlint-cli
        uses: nosborn/github-action-markdown-cli@v3.2.0
        with:
          files: docs
          config_file: .markdownlint.yaml
          ignore_path: .markdownlintignore

  deploy:
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Setup Pages
        uses: actions/configure-pages@v2

      - name: setup node
        uses: volta-cli/action@v3

      - name: cache node_modules
        uses: actions/cache@v3
        with:
          path: "**/.yarn"
          key: ${{ runner.os }}-modules-${{ hashFiles('**/yarn.lock') }}

      - name: Install deps
        run: yarn install --immutable

      - name: Build project
        run: yarn build

      - name: Upload artifact
        if: startsWith(github.head_ref, 'refs/heads/master')
        uses: actions/upload-pages-artifact@v1
        with:
          # Upload entire repository
          path: "build"

      - name: Deploy to GitHub Pages
        if: startsWith(github.head_ref, 'refs/heads/master')
        id: deployment
        uses: actions/deploy-pages@v1
